import type { Notification, NotificationType, Announcement } from './types';

const mockNotifications: Notification[] = [
  {
    id: 'noti-1',
    brandId: 'brand-1',
    recipientId: 'user-1',
    type: 'sales_alert',
    title: '일일 매출 목표 달성',
    message: '강남점이 오늘 일일 매출 목표 500만원을 달성했습니다.',
    isRead: false,
    data: { storeId: 'store-1', storeName: '강남점', amount: 5000000 },
    createdAt: '2026-03-15T09:30:00Z',
  },
  {
    id: 'noti-2',
    brandId: 'brand-1',
    recipientId: 'user-1',
    type: 'inventory_alert',
    title: '재고 부족 알림',
    message: '홍대점의 닭가슴살 재고가 최소 수량(10kg) 이하로 떨어졌습니다.',
    isRead: false,
    data: { storeId: 'store-2', storeName: '홍대점', itemName: '닭가슴살', currentStock: 5 },
    createdAt: '2026-03-15T08:15:00Z',
  },
  {
    id: 'noti-3',
    brandId: 'brand-1',
    recipientId: 'user-1',
    type: 'inspection_due',
    title: '위생 점검 예정',
    message: '명동점의 정기 위생 점검이 3일 후 예정되어 있습니다.',
    isRead: false,
    data: { storeId: 'store-3', storeName: '명동점', dueDate: '2026-03-18' },
    createdAt: '2026-03-15T07:00:00Z',
  },
  {
    id: 'noti-4',
    brandId: 'brand-1',
    recipientId: 'user-1',
    type: 'review_new',
    title: '새로운 리뷰 등록',
    message: '잠실점에 네이버 리뷰가 새로 등록되었습니다. 평점: 4.5',
    isRead: true,
    data: { storeId: 'store-4', storeName: '잠실점', rating: 4.5, source: 'naver' },
    createdAt: '2026-03-14T22:30:00Z',
  },
  {
    id: 'noti-5',
    brandId: 'brand-1',
    recipientId: 'user-1',
    type: 'staff_absence',
    title: '직원 결근 알림',
    message: '신촌점 홍길동 직원이 금일 결근 처리되었습니다.',
    isRead: false,
    data: { storeId: 'store-5', storeName: '신촌점', staffName: '홍길동' },
    createdAt: '2026-03-14T21:00:00Z',
  },
  {
    id: 'noti-6',
    brandId: 'brand-1',
    recipientId: 'user-1',
    type: 'system',
    title: '시스템 업데이트 안내',
    message: '3월 20일 02:00~04:00 시스템 정기 점검이 예정되어 있습니다.',
    isRead: true,
    data: { maintenanceDate: '2026-03-20' },
    createdAt: '2026-03-14T18:00:00Z',
  },
  {
    id: 'noti-7',
    brandId: 'brand-1',
    recipientId: 'user-1',
    type: 'sales_alert',
    title: '매출 급감 경고',
    message: '이태원점의 금주 매출이 전주 대비 30% 감소했습니다.',
    isRead: false,
    data: { storeId: 'store-6', storeName: '이태원점', decreaseRate: 30 },
    createdAt: '2026-03-14T17:00:00Z',
  },
  {
    id: 'noti-8',
    brandId: 'brand-1',
    recipientId: 'user-1',
    type: 'inventory_alert',
    title: '발주 승인 요청',
    message: '건대점에서 식자재 발주 요청이 접수되었습니다. 총 금액: 150만원',
    isRead: true,
    data: { storeId: 'store-7', storeName: '건대점', amount: 1500000 },
    createdAt: '2026-03-14T15:30:00Z',
  },
  {
    id: 'noti-9',
    brandId: 'brand-1',
    recipientId: 'user-1',
    type: 'review_new',
    title: '부정 리뷰 알림',
    message: '여의도점에 1점 리뷰가 등록되었습니다. 빠른 확인이 필요합니다.',
    isRead: false,
    data: { storeId: 'store-8', storeName: '여의도점', rating: 1, source: 'google' },
    createdAt: '2026-03-14T14:00:00Z',
  },
  {
    id: 'noti-10',
    brandId: 'brand-1',
    recipientId: 'user-1',
    type: 'inspection_due',
    title: '점검 결과 보고',
    message: '강남점 위생 점검이 완료되었습니다. 총점: 92/100',
    isRead: true,
    data: { storeId: 'store-1', storeName: '강남점', score: 92 },
    createdAt: '2026-03-14T12:00:00Z',
  },
  {
    id: 'noti-11',
    brandId: 'brand-1',
    recipientId: 'user-1',
    type: 'staff_absence',
    title: '지각 알림',
    message: '홍대점 박서준 직원이 30분 지각했습니다.',
    isRead: false,
    data: { storeId: 'store-2', storeName: '홍대점', staffName: '박서준', minutes: 30 },
    createdAt: '2026-03-14T10:30:00Z',
  },
  {
    id: 'noti-12',
    brandId: 'brand-1',
    recipientId: 'user-1',
    type: 'system',
    title: '새 기능 추가',
    message: '재고 자동 발주 기능이 추가되었습니다. 설정에서 활성화해주세요.',
    isRead: true,
    data: { featureName: 'auto-order' },
    createdAt: '2026-03-13T16:00:00Z',
  },
  {
    id: 'noti-13',
    brandId: 'brand-1',
    recipientId: 'user-1',
    type: 'sales_alert',
    title: '월간 매출 리포트',
    message: '2월 전체 매출 리포트가 생성되었습니다. 총 매출: 2.3억원',
    isRead: true,
    data: { month: '2026-02', totalSales: 230000000 },
    createdAt: '2026-03-13T09:00:00Z',
  },
  {
    id: 'noti-14',
    brandId: 'brand-1',
    recipientId: 'user-1',
    type: 'inventory_alert',
    title: '유통기한 임박',
    message: '명동점의 소스류 3개 품목이 유통기한 7일 이내입니다.',
    isRead: false,
    data: { storeId: 'store-3', storeName: '명동점', itemCount: 3 },
    createdAt: '2026-03-13T08:00:00Z',
  },
  {
    id: 'noti-15',
    brandId: 'brand-1',
    recipientId: 'user-1',
    type: 'review_new',
    title: '리뷰 답변 필요',
    message: '잠실점에 미답변 리뷰가 5건 있습니다.',
    isRead: true,
    data: { storeId: 'store-4', storeName: '잠실점', unrepliedCount: 5 },
    createdAt: '2026-03-12T20:00:00Z',
  },
  {
    id: 'noti-16',
    brandId: 'brand-1',
    recipientId: 'user-1',
    type: 'staff_absence',
    title: '연차 신청',
    message: '강남점 김하늘 직원이 3/20~3/21 연차를 신청했습니다.',
    isRead: false,
    data: { storeId: 'store-1', storeName: '강남점', staffName: '김하늘', startDate: '2026-03-20', endDate: '2026-03-21' },
    createdAt: '2026-03-12T16:00:00Z',
  },
  {
    id: 'noti-17',
    brandId: 'brand-1',
    recipientId: 'user-1',
    type: 'sales_alert',
    title: '주말 매출 증가',
    message: '전 매장 주말 평균 매출이 전주 대비 15% 증가했습니다.',
    isRead: true,
    data: { increaseRate: 15 },
    createdAt: '2026-03-12T10:00:00Z',
  },
  {
    id: 'noti-18',
    brandId: 'brand-1',
    recipientId: 'user-1',
    type: 'inspection_due',
    title: '소방 점검 일정',
    message: '전 매장 소방 안전 점검이 3월 25일로 예정되어 있습니다.',
    isRead: false,
    data: { dueDate: '2026-03-25' },
    createdAt: '2026-03-12T09:00:00Z',
  },
  {
    id: 'noti-19',
    brandId: 'brand-1',
    recipientId: 'user-1',
    type: 'system',
    title: '비밀번호 변경 권고',
    message: '마지막 비밀번호 변경으로부터 90일이 경과했습니다. 변경을 권장합니다.',
    isRead: true,
    data: {},
    createdAt: '2026-03-11T14:00:00Z',
  },
  {
    id: 'noti-20',
    brandId: 'brand-1',
    recipientId: 'user-1',
    type: 'inventory_alert',
    title: '재고 실사 완료',
    message: '건대점 월간 재고 실사가 완료되었습니다. 차이 품목: 2건',
    isRead: true,
    data: { storeId: 'store-7', storeName: '건대점', discrepancyCount: 2 },
    createdAt: '2026-03-11T11:00:00Z',
  },
  {
    id: 'noti-21',
    brandId: 'brand-1',
    recipientId: 'user-1',
    type: 'review_new',
    title: '베스트 리뷰 선정',
    message: '강남점 3월 베스트 리뷰가 선정되었습니다.',
    isRead: true,
    data: { storeId: 'store-1', storeName: '강남점' },
    createdAt: '2026-03-11T09:00:00Z',
  },
  {
    id: 'noti-22',
    brandId: 'brand-1',
    recipientId: 'user-1',
    type: 'sales_alert',
    title: '점심 매출 속보',
    message: '수원점 점심 매출이 역대 최고를 기록했습니다. 매출: 180만원',
    isRead: false,
    data: { storeId: 'store-10', storeName: '수원점', amount: 1800000 },
    createdAt: '2026-03-10T14:00:00Z',
  },
  {
    id: 'noti-23',
    brandId: 'brand-1',
    recipientId: 'user-1',
    type: 'staff_absence',
    title: '신규 직원 입사',
    message: '여의도점에 신규 직원 이수진님이 입사했습니다.',
    isRead: true,
    data: { storeId: 'store-8', storeName: '여의도점', staffName: '이수진' },
    createdAt: '2026-03-10T09:00:00Z',
  },
  {
    id: 'noti-24',
    brandId: 'brand-1',
    recipientId: 'user-1',
    type: 'inspection_due',
    title: '점검 항목 업데이트',
    message: '위생 점검 체크리스트가 업데이트되었습니다. 5개 항목이 추가되었습니다.',
    isRead: false,
    data: { addedItems: 5 },
    createdAt: '2026-03-09T15:00:00Z',
  },
  {
    id: 'noti-25',
    brandId: 'brand-1',
    recipientId: 'user-1',
    type: 'system',
    title: '데이터 백업 완료',
    message: '3월 9일 전체 데이터 백업이 정상적으로 완료되었습니다.',
    isRead: true,
    data: { backupDate: '2026-03-09' },
    createdAt: '2026-03-09T06:00:00Z',
  },
  {
    id: 'noti-26',
    brandId: 'brand-1',
    recipientId: 'user-1',
    type: 'sales_alert',
    title: '신메뉴 판매 현황',
    message: '신메뉴 "트러플 파스타" 출시 첫 주 판매량: 320개',
    isRead: true,
    data: { menuName: '트러플 파스타', salesCount: 320 },
    createdAt: '2026-03-08T17:00:00Z',
  },
  {
    id: 'noti-27',
    brandId: 'brand-1',
    recipientId: 'user-1',
    type: 'inventory_alert',
    title: '긴급 발주 필요',
    message: '신촌점 음료 원재료가 소진 임박입니다. 즉시 발주가 필요합니다.',
    isRead: false,
    data: { storeId: 'store-5', storeName: '신촌점', itemName: '음료 원재료' },
    createdAt: '2026-03-08T11:00:00Z',
  },
  {
    id: 'noti-28',
    brandId: 'brand-1',
    recipientId: 'user-1',
    type: 'review_new',
    title: '리뷰 평점 하락',
    message: '홍대점의 월 평균 리뷰 평점이 4.2에서 3.8로 하락했습니다.',
    isRead: false,
    data: { storeId: 'store-2', storeName: '홍대점', previousRating: 4.2, currentRating: 3.8 },
    createdAt: '2026-03-08T09:00:00Z',
  },
  {
    id: 'noti-29',
    brandId: 'brand-1',
    recipientId: 'user-1',
    type: 'staff_absence',
    title: '근무 교대 요청',
    message: '명동점 최유리 직원이 3/15 근무 교대를 요청했습니다.',
    isRead: true,
    data: { storeId: 'store-3', storeName: '명동점', staffName: '최유리', date: '2026-03-15' },
    createdAt: '2026-03-07T16:00:00Z',
  },
  {
    id: 'noti-30',
    brandId: 'brand-1',
    recipientId: 'user-1',
    type: 'system',
    title: '앱 버전 업데이트',
    message: 'DDUNDDUN v2.5.0이 출시되었습니다. 새로운 대시보드 기능을 확인해보세요.',
    isRead: true,
    data: { version: '2.5.0' },
    createdAt: '2026-03-07T10:00:00Z',
  },
  {
    id: 'noti-31',
    brandId: 'brand-1',
    recipientId: 'user-1',
    type: 'sales_alert',
    title: '프로모션 효과 분석',
    message: '봄맞이 프로모션 기간 매출이 평소 대비 25% 증가했습니다.',
    isRead: true,
    data: { promotionName: '봄맞이 프로모션', increaseRate: 25 },
    createdAt: '2026-03-06T15:00:00Z',
  },
];

const mockAnnouncements: Announcement[] = [
  {
    id: 'ann-1',
    brandId: 'brand-1',
    authorId: 'user-1',
    authorName: '본사 관리팀',
    title: '2026년 봄 시즌 신메뉴 출시 안내',
    content: '안녕하세요, 본사 관리팀입니다.\n\n2026년 봄 시즌 신메뉴가 3월 20일부터 전 매장에 순차 적용됩니다.\n\n신메뉴 목록:\n1. 트러플 크림 파스타\n2. 봄나물 비빔밥\n3. 딸기 라떼\n4. 체리 블라썸 에이드\n\n각 매장에서는 교육 자료를 확인하시고, 출시 전까지 직원 교육을 완료해주시기 바랍니다.\n\n문의사항은 본사 메뉴개발팀(내선 305)으로 연락주세요.',
    priority: 'high',
    targetRole: 'all',
    isPinned: true,
    publishedAt: '2026-03-14T10:00:00Z',
    createdAt: '2026-03-14T09:30:00Z',
  },
  {
    id: 'ann-2',
    brandId: 'brand-1',
    authorId: 'user-1',
    authorName: '본사 관리팀',
    title: '3월 정기 위생 점검 일정 공지',
    content: '3월 정기 위생 점검이 아래 일정으로 진행됩니다.\n\n- 1주차 (3/18~3/19): 강남점, 홍대점, 명동점\n- 2주차 (3/25~3/26): 잠실점, 신촌점, 건대점\n- 3주차 (4/1~4/2): 여의도점, 수원점\n\n점검 전 자체 체크리스트를 활용하여 사전 점검을 진행해주세요.',
    priority: 'high',
    targetRole: 'all',
    isPinned: true,
    publishedAt: '2026-03-13T14:00:00Z',
    createdAt: '2026-03-13T13:30:00Z',
  },
  {
    id: 'ann-3',
    brandId: 'brand-1',
    authorId: 'user-1',
    authorName: '인사팀',
    title: '가맹점주 간담회 개최 안내',
    content: '2026년 상반기 가맹점주 간담회를 아래와 같이 개최합니다.\n\n일시: 2026년 3월 28일(토) 14:00\n장소: 본사 대회의실\n안건: 상반기 운영 계획, 신메뉴 전략, 의견 수렴\n\n참석 여부를 3월 22일까지 회신해주세요.',
    priority: 'normal',
    targetRole: 'owner',
    isPinned: false,
    publishedAt: '2026-03-12T11:00:00Z',
    createdAt: '2026-03-12T10:30:00Z',
  },
  {
    id: 'ann-4',
    brandId: 'brand-1',
    authorId: 'user-1',
    authorName: '본사 관리팀',
    title: 'POS 시스템 업데이트 안내',
    content: 'POS 시스템 업데이트가 3월 17일(화) 새벽 2시에 진행됩니다.\n\n업데이트 내용:\n- 결제 속도 개선\n- 신규 할인 쿠폰 기능 추가\n- 영수증 디자인 변경\n\n업데이트는 자동으로 적용되며, 영업시간에는 영향이 없습니다.',
    priority: 'normal',
    targetRole: 'all',
    isPinned: false,
    publishedAt: '2026-03-11T09:00:00Z',
    createdAt: '2026-03-11T08:30:00Z',
  },
  {
    id: 'ann-5',
    brandId: 'brand-1',
    authorId: 'user-1',
    authorName: '인사팀',
    title: '3월 직원 교육 일정',
    content: '3월 정기 직원 교육이 아래와 같이 진행됩니다.\n\n- 서비스 매뉴얼 교육: 3/19(수) 10:00~12:00\n- 식품 안전 교육: 3/20(목) 14:00~16:00\n- 신메뉴 조리 교육: 3/21(금) 10:00~15:00\n\n각 매장 매니저는 직원 참석 관리를 부탁드립니다.',
    priority: 'normal',
    targetRole: 'manager',
    isPinned: false,
    publishedAt: '2026-03-10T15:00:00Z',
    createdAt: '2026-03-10T14:30:00Z',
  },
  {
    id: 'ann-6',
    brandId: 'brand-1',
    authorId: 'user-1',
    authorName: '본사 관리팀',
    title: '봄맞이 프로모션 운영 가이드',
    content: '3월 15일부터 4월 15일까지 진행되는 봄맞이 프로모션 운영 가이드입니다.\n\n1. 봄 시즌 세트 메뉴 10% 할인\n2. SNS 인증 이벤트 (음료 무료 제공)\n3. 스탬프 2배 적립\n\n프로모션 POP 물품은 3월 14일까지 각 매장에 배송 완료 예정입니다.',
    priority: 'normal',
    targetRole: 'all',
    isPinned: false,
    publishedAt: '2026-03-09T10:00:00Z',
    createdAt: '2026-03-09T09:30:00Z',
  },
  {
    id: 'ann-7',
    brandId: 'brand-1',
    authorId: 'user-1',
    authorName: '본사 관리팀',
    title: '식자재 가격 인상 안내',
    content: '주요 식자재 공급가가 4월부터 인상될 예정입니다.\n\n- 닭가슴살: 8% 인상\n- 올리브유: 5% 인상\n- 밀가루: 3% 인상\n\n원가 관리에 참고해주시기 바랍니다. 대체 공급업체 검토 중이며, 결과는 추후 안내드리겠습니다.',
    priority: 'high',
    targetRole: 'owner',
    isPinned: false,
    publishedAt: '2026-03-08T14:00:00Z',
    createdAt: '2026-03-08T13:30:00Z',
  },
  {
    id: 'ann-8',
    brandId: 'brand-1',
    authorId: 'user-1',
    authorName: '인사팀',
    title: '알바 채용 공고 템플릿 배포',
    content: '매장별 아르바이트 채용 시 활용할 수 있는 공고 템플릿을 배포합니다.\n\n첨부 파일을 다운로드하여 매장 정보에 맞게 수정 후 사용해주세요.\n\n채용 관련 문의: 인사팀 내선 201',
    priority: 'low',
    targetRole: 'manager',
    isPinned: false,
    publishedAt: '2026-03-07T11:00:00Z',
    createdAt: '2026-03-07T10:30:00Z',
  },
  {
    id: 'ann-9',
    brandId: 'brand-1',
    authorId: 'user-1',
    authorName: '본사 관리팀',
    title: '매장 청소 체크리스트 개정',
    content: '매장 일일 청소 체크리스트가 개정되었습니다.\n\n주요 변경사항:\n- 화장실 점검 항목 세분화 (3개 -> 6개)\n- 주방 그리스 트랩 청소 주기 변경 (주1회 -> 주2회)\n- 테이블 소독 기록 추가\n\n개정된 체크리스트는 시스템에서 확인 가능합니다.',
    priority: 'low',
    targetRole: 'staff',
    isPinned: false,
    publishedAt: '2026-03-06T09:00:00Z',
    createdAt: '2026-03-06T08:30:00Z',
  },
  {
    id: 'ann-10',
    brandId: 'brand-1',
    authorId: 'user-1',
    authorName: '본사 관리팀',
    title: '2월 우수 매장 시상 안내',
    content: '2월 우수 매장 시상 결과를 안내드립니다.\n\n매출 우수: 강남점 (월 매출 8,200만원)\n서비스 우수: 잠실점 (고객 만족도 4.9)\n위생 우수: 명동점 (위생 점검 100점)\n\n수상 매장에는 인센티브가 지급됩니다. 축하드립니다!',
    priority: 'normal',
    targetRole: 'all',
    isPinned: false,
    publishedAt: '2026-03-05T10:00:00Z',
    createdAt: '2026-03-05T09:30:00Z',
  },
  {
    id: 'ann-11',
    brandId: 'brand-1',
    authorId: 'user-1',
    authorName: '본사 관리팀',
    title: '배달 플랫폼 수수료 협상 결과',
    content: '주요 배달 플랫폼과의 수수료 재협상 결과를 안내드립니다.\n\n- 배달의민족: 기존 15% -> 13% (2% 인하)\n- 쿠팡이츠: 기존 12% -> 11% (1% 인하)\n- 요기요: 기존 14% -> 13% (1% 인하)\n\n변경된 수수료율은 4월 1일부터 적용됩니다.',
    priority: 'normal',
    targetRole: 'owner',
    isPinned: false,
    publishedAt: '2026-03-04T16:00:00Z',
    createdAt: '2026-03-04T15:30:00Z',
  },
];

let notifications = [...mockNotifications];
let announcements = [...mockAnnouncements];

export function getNotifications(filters?: { type?: string; isRead?: string }): Notification[] {
  let result = [...notifications];

  if (filters?.type && filters.type !== 'all') {
    result = result.filter((n) => n.type === filters.type);
  }

  if (filters?.isRead === 'read') {
    result = result.filter((n) => n.isRead);
  } else if (filters?.isRead === 'unread') {
    result = result.filter((n) => !n.isRead);
  }

  return result.sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime());
}

export function getUnreadCount(): number {
  return notifications.filter((n) => !n.isRead).length;
}

export function markAsRead(id: string): void {
  notifications = notifications.map((n) =>
    n.id === id ? { ...n, isRead: true } : n
  );
}

export function markAllAsRead(): void {
  notifications = notifications.map((n) => ({ ...n, isRead: true }));
}

export function getAnnouncements(): Announcement[] {
  return [...announcements].sort((a, b) => {
    if (a.isPinned !== b.isPinned) return a.isPinned ? -1 : 1;
    return new Date(b.publishedAt).getTime() - new Date(a.publishedAt).getTime();
  });
}

export function getAnnouncementById(id: string): Announcement | undefined {
  return announcements.find((a) => a.id === id);
}

export function createAnnouncement(data: {
  title: string;
  content: string;
  priority: Announcement['priority'];
  targetRole: Announcement['targetRole'];
  isPinned: boolean;
}): Announcement {
  const announcement: Announcement = {
    id: `ann-${Date.now()}`,
    brandId: 'brand-1',
    authorId: 'user-1',
    authorName: '본사 관리팀',
    title: data.title,
    content: data.content,
    priority: data.priority,
    targetRole: data.targetRole,
    isPinned: data.isPinned,
    publishedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  };
  announcements = [announcement, ...announcements];
  return announcement;
}
